on: [push, pull_request]

name: Create App Bundle

jobs:
  bundle:
    name: Bundle on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install briefcase
          python -m pip freeze
      - name: Create and Build Bundle
        run: |
          briefcase create
          cp src/savesync/resources/bin/* linux/appimage/EmuDeck\ SaveSync/EmuDeck\ SaveSync.AppDir/usr/bin/
          briefcase build
      - name: Package
        run: briefcase package
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: EmuDeck-SaveSync-AppImage
          path: '**/*.AppImage'